apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myvertx
  name: myvertx
  namespace: kubedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myvertx  
  template:
    metadata:
      labels:
        app: myvertx
    spec:    
      containers:
        - name: myvertx        
          image: burr/myvertx:v1
          livenessProbe:
            httpGet:
              port: http
              path: /hello
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3          
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          ports:
          - containerPort: 8080
      